#!/bin/sh

indexFile="${SMARKY_INDEX:-${XDG_DATA_HOME:-$HOME/.local/share}/smarky-index}"

usage() {
  echo "Usage information:"
  echo "  smarky create [command] [description] -- add a command to the index"
  echo "  smarky remove [index|description] ------ remove command from index"
  echo "  smarky list ---------------------------- list all added commands"
  echo "  smarky [help|usage|etc.] --------------- display usage information"
}

create() {
  echo "NOT IMPLEMENTED" >&2
}

remove() {
  echo "NOT IMPLEMENTED" >&2
}

list() {
  echo "NOT IMPLEMENTED" >&2
}

main() {
  case "$1" in
    create|add) shift; create "$@" ;;
    remove|del) shift; remove "$@" ;;
    list|show)  shift; list "$@" ;;
    *) usage
  esac
}

main "$@"
