name: CI

on:
  pull_request: {}
  push:
    branches: [ master ]

jobs:
  bats:
    name: BATS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout files in the repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install sqlite3
        run: sudo apt-get install sqlite3

      - name: Run tests with BATS
        run: ./test/bats/bin/bats ./test/smarky.bats

  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout files in the repository
        uses: actions/checkout@v3

      - name: Analyze files with ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths: zsh
          severity: warning
